---
title: "LSE Risk"
output: pdf_document
---

```{r, echo=FALSE, warning=FALSE, message=F}
source('loadUp.R')
library(xtable)
library(xts)
library(PerformanceAnalytics)
subs = loadSubAdvisors()
subs.o = organizeSubs(subs)
subs.w = getAllocations()
lse.w =  sapply(as.character.factor(subs.w$LSE$Name),  function(x)return(which(names(subs.o$LSE)==x)))
lse.cctr.126 = rollCCTR(na.omit(subs.o$LSE), weights = lse.w, initialWindow = 126)
lse.cctr.126 = cbind(lse.cctr.126, xts(apply(lse.cctr.126, 1, sum), order.by = index(lse.cctr.126)))
names(lse.cctr.126)[ncol(lse.cctr.126)] = "Total"
lse.cctr.63 = rollCCTR(na.omit(subs.o$LSE), weights = lse.w, initialWindow = 63)
lse.cctr.63 = cbind(lse.cctr.63, xts(apply(lse.cctr.63, 1, sum), order.by = index(lse.cctr.63)))
names(lse.cctr.63)[ncol(lse.cctr.63)] = "Total"
lse.126.cctr.table = xtable(as.data.frame(lse.cctr.126[endpoints(lse.cctr.126, on = "months"),]), align = "lrrrrrrrr",  digits = 3)
lse.mctr.126 = lse.cctr.126[nrow(lse.cctr.126), 1:(ncol(lse.cctr.126)-1)]/lse.w
lse.mctr.63 = lse.cctr.63[nrow(lse.cctr.63), 1:(ncol(lse.cctr.63)-1)]/lse.w
lse.63.cctr.table = xtable(as.data.frame(lse.cctr.63[endpoints(lse.cctr.63, on = "months"),]), align = "lrrrrrrrr",  digits = 3)
lse.63.mctr.table = xtable(as.data.frame(lse.mctr.63), align = "lrrrrrrr",  digits = 3)
lse.126.mctr.table = xtable(as.data.frame(lse.mctr.126), align = "lrrrrrrr",  digits = 3)      
```

You can also embed plots, for example:

```{r, echo=FALSE}
plot(cars)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
