#IMPORT NAMESPACES
library(xts)
library(PerformanceAnalytics)
library(magrittr)
library(factorAnalytics)
library(quantmod)

#LOAD USER-DEFINED FUNCTIONS
source('Functions/apply.rolling2.R')
source('Functions/executeSP.R')
source('Functions/loadSubAdvisors.R')
source('Functions/loadSubAdvisor.R')
source('Functions/organizeSubs.R')
source('Functions/loadUFTs.R')
source('Functions/loadPOFs.R')
source('Functions/loadIndices.R')
source('Functions/nVaR.R')
source('Functions/mVaR.R')
source('Functions/nVaRBounds.R')
source('Functions/mVaRBounds.R')
source('Functions/compareLevels.R')
source('Functions/compareLevels2.R')
source('Functions/currentLevelsSubs.R')
source('Functions/currentLevelsSubs2.R')
source('Functions/currentLevelsFunds.R')
source('Functions/currentLevelsFunds2.R')
source('Functions/dailyExceptions.R')
source('Functions/dailyVaRBounds.R')
source('Functions/organizeExceptions.R')
source('Functions/organizeLevels.R')
source('Functions/getSpSectors.R')
source('Functions/getSpReturns.R')
source('Functions/getFIReturns.R')
source('Functions/getHYReturns.R')
source('Functions/getMarketReturns.R')
source('Functions/rollCCTR.R')
source('Functions/rollTsfm2.R')
source('Functions/rollFmVaRdecomp.R')
source('Functions/rollFmESdecomp.R')
source('Functions/runTsFactorModel.R')
source('Functions/extractSingleVaRroll.R')
source('Functions/extractSingleBetaroll.R')
source('Functions/extractFieldFromRoll.R')
source('Functions/createTimeSlices2.R')
source('Functions/getAllocations.R')
source('Functions/getAllocations_Rolling.R')
source('Functions/getWeights.R')
source('Functions/getComponentRisk.R')
source('Functions/organizeComponentRisks.R')
source('Functions/reportComponentRisks.R')
source('Functions/getAvgCor.R')
source('Functions/reportAvgCorToBM.R')
source('Functions/rollAvgCorToBM.R')
source('Functions/rollingCorrelationMatrix.R')
source('Functions/extractAvgCorrelation.R')
source('Functions/reportAvgCorrelation.R')
source('Functions/reportCorrelation.R')
source('Functions/getQuandlKey.R')
source('Functions/weightedPortfolios.R')
source('Functions/levelsForBarPlot.R')
source('Functions/ewmaModel.R')
source('Functions/sectorExposure.R')
source('Functions/rollingStats.R')
source('Functions/charts.AlphaBeta.R')
source('Functions/charts.PerformanceSummary2.R')
#GET DATA OBJECTS
subs = loadSubAdvisors()
allocations = getAllocations(end(subs))
subs.o = organizeSubs(subs, curMgrs = T, allocations = allocations)
subs.weights = getWeights(subs.o)
#subs.weights$MF = subs.weights$MF[-which(names(subs.weights$MF)=="Centurion")]
#subs.weights$MF = subs.weights$MF/sum(subs.weights$MF)
ufts = loadUFTs()
pofs = loadPOFs()
inds = loadIndices()
mkt = getMarketReturns(inds)
sp = mkt$SPTR
sp2 = getSpReturns2()

if(end(sp2) > end(sp)){sp = rbind(sp, sp2[which(index(sp2)>end(sp))])}
sp.sectors = getSpSectors(inds)
hy = getHYReturns(inds)

#source('Functions/nVaRExceptions.R')
#source('Functions/rollVaR.R')


# source('Functions/getFama3.R')
# source('Functions/currentVaRLevels.R')
# source('Functions/plotBounds.R')
# source('Functions/printBounds.R')
# source('Functions/cbind.lag.R')



