---
output: pdf_document
---
#Long/Short Equity - Risk Contribution


```{r, echo=FALSE, warning=FALSE, message=F}
source('loadUp.R')
library(xtable)
options(xtable.comment = F)
library(xts)
library(PerformanceAnalytics)
subs = loadSubAdvisors()
subs.o = organizeSubs(subs)
subs.w = getAllocations()
lse.w =  sapply(names(subs.o$LSE),  function(x)return(which(subs.w$LSE$Name==x)))
lse.w = subs.w$LSE[lse.w, 3]
lse.cctr.126 = extractFieldFromRoll(rollCCTR(na.omit(subs.o$LSE), weights = lse.w, initialWindow = 126), 'contribution')

lse.cctr.126 = cbind(lse.cctr.126, xts(apply(lse.cctr.126, 1, sum), order.by = index(lse.cctr.126)))

names(lse.cctr.126)[ncol(lse.cctr.126)] = "Total"

lse.cctr.63= extractFieldFromRoll(rollCCTR(na.omit(subs.o$LSE), weights = lse.w, initialWindow = 63), 'contribution')

lse.cctr.63 = cbind(lse.cctr.63, xts(apply(lse.cctr.63, 1, sum), order.by = index(lse.cctr.63)))

names(lse.cctr.63)[ncol(lse.cctr.63)] = "Total"

lse.126.cctr.table = xtable(as.data.frame(lse.cctr.126[endpoints(lse.cctr.126, on = "quarters"),]*100), align = "lrrrrrrrr",  digits = 3, caption = "CCTR 126-day")

lse.mctr.126 = t(apply(lse.cctr.126[, 1:(ncol(lse.cctr.126)-1)], 1, function(x)return(x/lse.w)))
lse.mctr.63 = t(apply(lse.cctr.63[, 1:(ncol(lse.cctr.63)-1)], 1, function(x)return(x/lse.w)))

lse.63.cctr.table = xtable(as.data.frame(lse.cctr.63[endpoints(lse.cctr.63, on = "quarters"),]*100), align = "lrrrrrrrr",  digits = 3, caption = "CCTR 63-day")

lse.63.mctr.table = xtable(as.data.frame(lse.mctr.63[endpoints(lse.mctr.63, on = "quarters"),])*100, align = "lrrrrrrr",  digits = 3, caption = "MCTR 63-day")

lse.126.mctr.table = xtable(as.data.frame(lse.mctr.126[endpoints(lse.mctr.126, on = "quarters"),])*100, align = "lrrrrrrr",  digits = 3, caption = "MCTR 126-day")
```

## Conditional Contribution to Volatility
*Absolute contribution based on the current weights.*


 + 63-day
```{r, echo=FALSE, message=F, results='asis'}
print(lse.63.cctr.table, floating = F, caption.placement = "top")
```

 + 126-day
```{r, echo=FALSE, message=F, results='asis'}
print(lse.126.cctr.table, floating = F, caption.placement = "top")
```


```{r, echo=FALSE}
chart.TimeSeries(lse.cctr.63, main = "63d Rolling Contribution To Risk - Long/Short Equity", legend.loc = "bottomleft", colorset = rainbow8equal)

chart.TimeSeries(lse.cctr.126, main = "126d Rolling Contribution To Risk - Long/Short Equity", legend.loc = "bottomleft", colorset = rainbow8equal)
```




##  Marginal Contribution to Volatility @ Current Weights 
*Sensitivity of portfolio volatility to changes in allocations.*

 + 63-day
```{r, echo=FALSE, message=F, results='asis'}
print(lse.63.mctr.table, floating = F, caption.placement = "top")
```


 + 126-day
```{r, echo=FALSE, message=F, results='asis'}
print(lse.126.mctr.table, floating = F, caption.placement = "top")
```



```{r, echo=FALSE}
chart.TimeSeries(lse.mctr.63, main = "63d Rolling Marginal Contribution To Risk - Long/Short Equity", legend.loc = "bottomleft", colorset = rainbow8equal)

chart.TimeSeries(lse.cctr.126, main = "126d Rolling Marginal Contribution To Risk - Long/Short Equity", legend.loc = "bottomleft", colorset = rainbow8equal)
```



