---
output:
  pdf_document:
    keep_tex: yes
  html_document: default
  word_document: default
---

```{r, echo=FALSE, warning=FALSE, message=F, results='asis'}
source('loadUp.R')
library(xtable)
#GET DATA OBJECTS
# subs = loadSubAdvisors()
# subs.o = organizeSubs(subs)
# ufts = loadUFTs()
# pofs = loadPOFs()
# inds = loadIndices()

#SET OPTIONS
options(xtable.comment = F)
options(xtable.floating = F)
options(xtable.timestamp = "")
options(width = 100)

# # TESTS
# load(file = "hamfData2.RData")
# testDate = '/20160217'
# #GET VAR EXCEPTIONS - *****TESTDATE*****
# sub.exceptions = lapply(lapply(subs.o, dailyExceptions, date = end(subs[testDate])), function(x)return(x*100))
# pof.exceptions = dailyExceptions(pofs[testDate])*100
# uft.exceptions = dailyExceptions(ufts[testDate])*100

#GET VAR EXCEPTIONS
sub.exceptions = lapply(lapply(subs.o, dailyExceptions), function(x)return(x*100))
pof.exceptions = dailyExceptions(pofs)*100
uft.exceptions = dailyExceptions(ufts)*100

#ORGANIZE INTO DATAFRAME
exceptions = organizeExceptions(pof.exceptions, uft.exceptions, sub.exceptions)
```

##Daily 99% VaR Exceptions
### `r end(subs.o$LSE)`

```{r, echo=FALSE, warning=FALSE, message=F, results='asis'}
#MAKE xtable objects
exceptions.xList = xtableList(exceptions, align = 'rccc')

large = function(x){
    paste0('{\\Large{\\bfseries ', x, '}}')
}
italic = function(x){
    paste0('{\\emph{ ', x, '}}')
}
bold = function(x){
   paste0('{\\bfseries ', x, '}')
}
red = function(x){
   paste0('{\\color{red} ', x, '}')
}
print.xtableList(exceptions.xList
                 #, colnames.format = "multiple"
                 , sanitize.subheadings.function = italic
                 , sanitize.colnames.function = bold
                 #, sanitize.numbers()
                 , sanitize.rownames.function = bold
                 #, booktabs = T
                 #, table.placement = "Ht"
                 )
#print.xtableList(test.xList)
```





